# Generated by Django 2.1.5 on 2022-06-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='schediule',
            new_name='schedule',
        ),
    ]
